### ISSUE TITLE
Switch to another TOML package

### ISSUE THREAD

**Issue by mischkl** [dbohdan/remarshal#19]
The pytoml package that is currently used is deprecated; the recommended replacement is the [toml](https://github.com/uiri/toml) package. I believe that also implements indentation and the newest version of TOML, thus resolving #10 and #15.

**Comment by dbohdan** [comment]
I plan on switching away from pytoml.  A few months ago I evaluated the toml package and found it unsuitable due to https://github.com/uiri/toml/issues/201 and other issues.  I also didn't like that the serializer produced trailing whitespace.  I am waiting for another TOML package to mature.  The current candidates are https://github.com/alethiophile/qtoml or https://github.com/sdispater/tomlkit.

I'll keep this issue open but change the title to more general.

**Comment by bealdav** [comment]
and the winner is ?

**Comment by dbohdan** [comment]
@bealdav None so far.  qtoml does not support Python 2 and TOML Kit has a blocking issue (https://github.com/sdispater/tomlkit/issues/93).

**Comment by dbohdan** [comment]
I've switched to TOML Kit in the `master` branch.  Now remarshal supports TOML v1.0.0-rc1.  Please check if you have any problems with it.  If not, I'll release a new version soon.

**Comment by dbohdan** [comment]
[Published](https://pypi.org/project/remarshal/0.14.0/).
