### ISSUE TITLE
Feature Request: Support CBOR?

### ISSUE THREAD

**Issue by FGasper** [dbohdan/remarshal#22]
Would it be workable to add CBOR support to this tool?

**Comment by dbohdan** [comment]
What do you mean, "would it be workable"?

**Comment by FGasper** [comment]
I’m just requesting that CBOR be added as a 5th supported serialization.

**Comment by dbohdan** [comment]
I am not interested in adding CBOR myself because I don't use it.  I will merge a pull request adding CBOR support if it is of similar quality to the MessagePack support (handles binaries and strings correctly in Python 3, has tests).  You can look at https://github.com/dbohdan/remarshal/compare/f587cbd...6e57901 for reference.

**Comment by FGasper** [comment]
That sounds reasonable. I’ll see what I can do.

**Comment by dbohdan** [comment]
Added in [v0.12.0](https://github.com/dbohdan/remarshal/releases/tag/v0.12.0).
